### ISSUE TITLE
starting money

### ISSUE THREAD

**Issue by Kierenxcvi** [RLRP-Bugs/RLRP-Server#2]
**Describe the bug**
i dont seem to have any starting money

**How To Reproduce**
create a new character

**Screenshots**
N/A

**Additional context**
IVE CHECKED BANK AND CASH AND I HAVE NOTHING

**Comment by RLRP-Bugs** [comment]
I have fixed the issue sorry about that if you do not get the starting money after a server relog please open a ticket.

**Comment by Kierenxcvi** [comment]
situation solved

**Comment by RLRP-Bugs** [comment]
Fixed 20k starting
